---
- name: Install k8s-infra with Helm
  hosts: localhost
  gather_facts: false
  vars:
    release_name: "signoz-k8s-infra"
    namespace: "signoz-system"
    chart_repo: "signoz"
    chart_name: "k8s-infra"
    cluster_name: "local-cluster"
    deployment_environment: "development"
    # Get SigNoz endpoint from environment or use default
    signoz_endpoint: "{{ lookup('ansible.builtin.env', 'SIGNOZ_ENDPOINT') | default('host.docker.internal:4318', True) }}"
    
  tasks:
    - name: Add SigNoz Helm repository
      kubernetes.core.helm_repository:
        name: "{{ chart_repo }}"
        repo_url: "https://charts.signoz.io"
        
    - name: Update Helm repositories
      kubernetes.core.helm:
        name: dummy
        chart_ref: "{{ chart_repo }}/{{ chart_name }}"
        release_namespace: "{{ namespace }}"
        create_namespace: true
        state: absent
        wait: false
      ignore_errors: true
      
    - name: Create namespace if it doesn't exist
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        
    - name: Create values override file
      ansible.builtin.template:
        src: templates/values.yaml.j2
        dest: /tmp/k8s-infra-values.yaml
        
    - name: Install k8s-infra chart with custom values
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: "{{ chart_repo }}/{{ chart_name }}"
        release_namespace: "{{ namespace }}"
        create_namespace: true
        values_files:
          - /tmp/k8s-infra-values.yaml
        state: present
        wait: true
        timeout: 600s
        
    - name: Wait for OpenTelemetry Collector to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: DaemonSet
        namespace: "{{ namespace }}"
        label_selectors:
          - "app.kubernetes.io/component=opentelemetry-collector"
      register: collector_status
      until: collector_status.resources[0].status.numberReady == collector_status.resources[0].status.desiredNumberScheduled
      retries: 30
      delay: 10
      when: collector_status.resources | length > 0
      
    - name: Display installation status
      ansible.builtin.debug:
        msg: |
          k8s-infra installation completed successfully!
          Release name: {{ release_name }}
          Namespace: {{ namespace }}
          SigNoz endpoint: {{ signoz_endpoint }}
          
          To check the status, run:
          kubectl get pods -n {{ namespace }}
          kubectl get services -n {{ namespace }}
